services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis
    volumes:
      - redis-data:/data

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
# Names our volume
volumes:
  my-db:
  redis-data:
