name: test and push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-1:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello"
